# Generated by Django 5.0.2 on 2024-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_unique_identifier', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateField()),
                ('postcode', models.CharField(max_length=10)),
                ('property_type', models.CharField(max_length=50)),
                ('old_new', models.CharField(max_length=3)),
                ('duration', models.CharField(max_length=50)),
                ('primary_address', models.CharField(max_length=255)),
                ('secondary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('ppd_category_type', models.CharField(max_length=50)),
                ('record_status', models.CharField(max_length=50)),
            ],
        ),
    ]
