# Generated by Django 5.0.2 on 2024-03-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'managed': False},
        ),
    ]
